apiVersion: v1
kind: Service
metadata:
  name: e-track-app-svc
  namespace: e-track-dev
spec:
  selector:
    app: e-track-app
  type: LoadBalancer
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: e-track-app-svc
    port: 8080
    targetPort: 8080
    