apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-track-app-dep
  namespace: e-track-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: e-track-app
  template:
    metadata:
      labels:
        app: e-track-app
    spec:
      # ✅ Wait for MySQL to be ready before starting app
      initContainers:
        - name: wait-for-mysql
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z mysql-sfs 3306;
              do
                echo "Waiting for MySQL...";
                sleep 5;
              done;
              echo "MySQL is ready!"

      containers:
        - name: e-track-app
          image: sree471/e-track-app:latest
          imagePullPolicy: Always          # ✅ always pull latest image
          ports:
            - containerPort: 8080
          env:
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-vars
                  key: app-name
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-vars
                  key: db-host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-vars
                  key: db-port
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-vars
                  key: database-name
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: app-vars
                  key: db-username
            - name: APP_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-vars
                  key: app-port
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: sql-password
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "1Gi"

          