apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: e-track-dev
  labels:
    app: mysql-pvc
spec:
  storageClassName: mysql-premium-sc
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi