apiVersion: v1
kind: Service
metadata:
  name: mysql-sfs
  namespace: e-track-dev
spec:
  selector:
    app: mysql-sfs
  clusterIP: None
  ports:
  - name: mysql-svc
    port: 3306 
    targetPort: 3306
    