
services:

  # MySQL Database Service
  mysql:
    image: mysql:8-oracle
    container_name: mysql
    environment:
      MYSQL_DATABASE: expense_tracker
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - 3306:3306
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot123"]
      interval: 10s
      timeout: 5s
      retries: 10
  
  # application service
  expense_tracker:
    build:
      context: .
      dockerfile: Dockerfile.multi
    container_name: expense_tracker
    depends_on:
      - mysql
    ports:
      - 8080:8080
    environment:
      APP_NAME: Expense-Tracker
      DB_URL: jdbc:mysql://mysql:3306/expense_tracker
      DB_USERNAME: root
      DB_PASSWORD: root123
    networks:
      - backend

networks:
  backend:
    driver: bridge
