apiVersion: v1
kind: Service
metadata:
  name: e-track-app-svc
  namespace: e-track
spec:
  selector:
    app: e-track-app
  type: NodePort
  ports:
    - port: 8080          # ✅ fixed missing list syntax
      targetPort: 8080
      nodePort: 30080     # ✅ optional fixed port