name: sonar-test
on: 
  push:
    branches:
      - main
jobs:
  build:
    name: sonar build
    runs-on: ubuntu-latest

    steps:
      - name: get code
        uses: actions/checkout@v6.0.2

      - name: install java
        uses: actions/setup-java@v5.2.0
        with:
          java-version: '21'
          distribution: 'temurin' 
      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=java-project -Dsonar.projectName='java-project'
